# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Ahoj!
  displayName: 'Say hi'

- script: |
    echo Is this a real life.
    echo Is it just fantasy
  displayName: 'Run the intro'
